package com.pp.common.http.wanandroid.bean

/*
    {
				"adminAdd": false,
				"apkLink": "",
				"audit": 1,
				"author": "",
				"canEdit": false,
				"chapterId": 502,
				"chapterName": "自助",
				"collect": false,
				"courseId": 13,
				"desc": "",
				"descMd": "",
				"envelopePic": "",
				"fresh": false,
				"host": "",
				"id": 27001,
				"isAdminAdd": false,
				"link": "https://mp.weixin.qq.com/s/4eWuPTEw4Sgpi2VlBwWCUw",
				"niceDate": "2天前",
				"niceShareDate": "2天前",
				"origin": "",
				"prefix": "",
				"projectLink": "",
				"publishTime": 1691994344000,
				"realSuperChapterId": 493,
				"selfVisible": 0,
				"shareDate": 1691994344000,
				"shareUser": "小马快跑",
				"superChapterId": 494,
				"superChapterName": "广场Tab",
				"tags": [],
				"title": "超能力文本：探索Span机制的多彩世界（一）",
				"type": 0,
				"userId": 128797,
				"visible": 1,
				"zan": 0
			}
 */
data class ArticleBean(
    val adminAdd: Boolean = false,
    val apkLink: String = "",
    val audit: Int = 0,
    val author: String = "",
    val canEdit: Boolean = false,
    val chapterId: Int = 0,
    val chapterName: String = "",
    var collect: Boolean = false,
    val courseId: Int = 0,
    val desc: String = "",
    val descMd: String = "",
    val envelopePic: String = "",
    val fresh: Boolean = false,
    val host: String = "",
    val id: Int = 0,
    val isAdminAdd: Boolean = false,
    val link: String = "",
    val niceDate: String = "",
    val niceShareDate: String = "",
    val origin: String = "",
    val prefix: String = "",
    val projectLink: String = "",
    val publishTime: Long = 0,
    val realSuperChapterId: Int = 0,
    val selfVisible: Int = 0,
    val shareDate: Long = 0,
    val shareUser: String = "",
    val superChapterId: Int = 0,
    val superChapterName: String = "",
    val tags: List<Tag> = listOf(),
    val title: String = "",
    val type: Int = 0,
    val userId: Int = 0,
    val visible: Int = 0,
    val zan: Int = 0,
)